'''
json-import.py

Imports a matrix composition generated by rpi-display-editor
(https://github.com/jschuetter/rpi-display-editor)
and generates a Python file containing a Module instance with 
the corresponding components
'''

import os
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_DIR = os.path.join(ROOT_DIR, "matrix_display/modules/imports")

# Create output directory if does not exist
os.makedirs(DEFAULT_DIR, exist_ok=True)

