'''
Importer.py

Imports a matrix composition generated by rpi-display-editor
(https://github.com/jschuetter/rpi-display-editor)
and generates a Python file containing a Module instance with 
the corresponding components
'''

import os, json
from string import Template
from fractions import Fraction
from pathlib import Path
from typeguard import typechecked
from matrix_display.Components import *

ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_DIR = os.path.join(ROOT_DIR, "matrix_display/modules/imports")
BOILERPLATE_TEMPLATE_PATH = os.path.join(ROOT_DIR, "matrix_display/comp_boilerplate_template.py")

WIDGET_TYPES = {
    'TextWidget': Text,
    'ImgWidget': RasterImage
}

@typechecked
def from_json(comp_name: str, json_path: str, delay: float|Fraction|None = None):
    if not os.path.splitext(json_path)[1] == '.json': 
        raise ValueError("Please provide a path to a JSON file")

    # Create output directory if does not exist
    os.makedirs(DEFAULT_DIR, exist_ok=True)
        
    with open(json_path, 'r') as infile: 
        json_obj = json.load(infile)

    with open(BOILERPLATE_TEMPLATE_PATH, 'r') as infile: 
        boilerplate_template = Template(infile.read())

    kwarg_str = ''
    if delay: 
        kwarg_str += f", doLoop=True, delay={Fraction(delay)}"

    
        
    output_path = os.path.join(DEFAULT_DIR, comp_name + ".py")
    with open(output_path, 'w') as outfile: 
        # Get import lines & component definitions for all widgets
        imports = []
        components = []
        for widget in json_obj: 
            widget_t = WIDGET_TYPES[widget['type']]
            (widget_imports, widget_str) = widget_t.python_str(widget['params'])
            imports.append(widget_imports)
            components.append(widget_str)

        # Write boilerplate
        boilerplate = boilerplate_template.safe_substitute(compname=comp_name, kwargs=kwarg_str, imports='\n'.join(imports))
        outfile.write(boilerplate)

        # Append widget definitions to comopnents list
        for widget_str in components: 
            # Append widget lines to output file with proper indentation
            WIDGET_INDENT = 3  # Indentation level in 'components' list of class declaration
            INDENT = "    "
            for line in widget_str.splitlines(): 
                outfile.write("\n")
                outfile.write(INDENT * WIDGET_INDENT)
                outfile.write(line)
            outfile.write(",")

        # Close components list
        outfile.write("\n")
        outfile.write(INDENT * (WIDGET_INDENT-1))
        outfile.write("]")
            
